name: Test Docusaurus Build

on:
  pull_request:
    branches:
      - main # Csak a main (vagy master) branch-be irányuló PR-ek esetén

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install
      - name: Build API docs
        run: npm run docusaurus gen-api-docs all
      - name: Build
        run: npm run build